### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by cthoyt**
This pull request is part of an initiative to make the licensing information about OBO Foundry ontologies more actionable.

While this ontology contains licensing information in its metadata, GitHub is not aware of the license unless you create a `LICENSE` file with standardized text. This PR creates a `LICENSE` file with the standard text for the CC BY 4.0 license. 

More information about this initiative and further discussion is taking place here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1840.

### CODE REVIEW

**Comment by pfabry** [comment]
Licence added with update metadata

**Comment by cthoyt** [comment]
@pfabry I think there's a misunderstanding - having the license in the ontology's metadata itself is important, but so is having an explicit license file in the GitHub repository. This makes it so anyone who looks at the repository can understand the license without ontology-specific tooling. Therefore, it's worth having this file in addition to updating the ontology's metadata

**Comment by pfabry** [comment]
My bad! I didn't realize that and I will add it to other repos as well,

**Comment by cthoyt** [comment]
Thank you!

**Pull request merged**
